In [30]:
import zipfile

zip_path = "/content/[PUB] India_runs_data_and_ai_challenge.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/data")

print("Done!")

Done!

In [31]:
import os

os.listdir("/content")

['.config',
 '[PUB] India_runs_data_and_ai_challenge.zip',
 'data',
 'sample_data']

In [32]:
import os

path = "/content/[PUB] India_runs_data_and_ai_challenge.zip"

print("Exists:", os.path.exists(path))
print("Size (bytes):", os.path.getsize(path))
print("Size (MB):", os.path.getsize(path)/(1024*1024))

Exists: True
Size (bytes): 56725270
Size (MB): 54.09743309020996

In [33]:
!file "/content/[PUB] India_runs_data_and_ai_challenge.zip"

/content/[PUB] India_runs_data_and_ai_challenge.zip: Zip archive data, at least v2.0 to extract, compression method=store

In [34]:
import zipfile
import os

zip_path = "/content/[PUB] India_runs_data_and_ai_challenge.zip"
extract_path = "/content/data"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction Complete!")
print(os.listdir(extract_path))

Extraction Complete!
['[PUB] India_runs_data_and_ai_challenge', '__MACOSX']

In [35]:
import os

base_path = "/content/data/[PUB] India_runs_data_and_ai_challenge"

print(os.listdir(base_path))

['.DS_Store', 'India_runs_data_and_ai_challenge']

In [36]:
base_path = "/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge"

import os

print(os.listdir(base_path))

['submission_spec.docx', 'candidates.jsonl', 'sample_submission.csv', 'README.docx', 'redrob_signals_doc.docx', 'validate_submission.py', 'sample_candidates.json', 'submission_metadata_template.yaml', 'job_description.docx', 'candidate_schema.json']

In [37]:
import json

schema_path = "/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidate_schema.json"

with open(schema_path, "r") as f:
    schema = json.load(f)

print(schema.keys())

dict_keys(['$schema', 'title', 'description', 'type', 'required', 'properties'])

In [38]:
import pprint

pprint.pprint(schema)

{'$schema': 'http://json-schema.org/draft-07/schema#',
 'description': 'Schema for a single candidate profile in the Intelligent '
                'Candidate Discovery & Ranking Challenge dataset.',
 'properties': {'candidate_id': {'description': 'Unique identifier for the '
                                                'candidate. Format: '
                                                'CAND_XXXXXXX (7 digits).',
                                 'pattern': '^CAND_[0-9]{7}$',
                                 'type': 'string'},
                'career_history': {'items': {'properties': {'company': {'type': 'string'},
                                                            'company_size': {'enum': ['1-10',
                                                                                      '11-50',
                                                                                      '51-200',
                                                                                      '201-500',
                                                                                      '501-1000',
                                                                                      '1001-5000',
                                                                                      '5001-10000',
                                                                                      '10001+'],
                                                                             'type': 'string'},
                                                            'description': {'description': 'Role '
                                                                                           'responsibilities '
                                                                                           'and '
                                                                                           'achievements.',
                                                                            'type': 'string'},
                                                            'duration_months': {'minimum': 0,
                                                                                'type': 'integer'},
                                                            'end_date': {'format': 'date',
                                                                         'type': ['string',
                                                                                  'null']},
                                                            'industry': {'type': 'string'},
                                                            'is_current': {'type': 'boolean'},
                                                            'start_date': {'format': 'date',
                                                                           'type': 'string'},
                                                            'title': {'type': 'string'}},
                                             'required': ['company',
                                                          'title',
                                                          'start_date',
                                                          'end_date',
                                                          'duration_months',
                                                          'is_current',
                                                          'industry',
                                                          'company_size',
                                                          'description'],
                                             'type': 'object'},
                                   'maxItems': 10,
                                   'minItems': 1,
                                   'type': 'array'},
                'certifications': {'items': {'properties': {'issuer': {'type': 'string'},
                                                            'name': {'type': 'string'},
                                                            'year': {'type': 'integer'}},
                                             'required': ['name',
                                                          'issuer',
                                                          'year'],
                                             'type': 'object'},
                                   'type': 'array'},
                'education': {'items': {'properties': {'degree': {'type': 'string'},
                                                       'end_year': {'maximum': 2035,
                                                                    'minimum': 1970,
                                                                    'type': 'integer'},
                                                       'field_of_study': {'type': 'string'},
                                                       'grade': {'description': 'GPA '
                                                                                '/ '
                                                                                'percentage '
                                                                                '/ '
                                                                                'class.',
                                                                 'type': ['string',
                                                                          'null']},
                                                       'institution': {'type': 'string'},
                                                       'start_year': {'maximum': 2030,
                                                                      'minimum': 1970,
                                                                      'type': 'integer'},
                                                       'tier': {'description': 'Internal '
                                                                               'tiering '
                                                                               'for '
                                                                               'institution '
                                                                               'prestige.',
                                                                'enum': ['tier_1',
                                                                         'tier_2',
                                                                         'tier_3',
                                                                         'tier_4',
                                                                         'unknown'],
                                                                'type': 'string'}},
                                        'required': ['institution',
                                                     'degree',
                                                     'field_of_study',
                                                     'start_year',
                                                     'end_year'],
                                        'type': 'object'},
                              'maxItems': 5,
                              'minItems': 0,
                              'type': 'array'},
                'languages': {'items': {'properties': {'language': {'type': 'string'},
                                                       'proficiency': {'enum': ['basic',
                                                                                'conversational',
                                                                                'professional',
                                                                                'native'],
                                                                       'type': 'string'}},
                                        'required': ['language', 'proficiency'],
                                        'type': 'object'},
                              'type': 'array'},
                'profile': {'properties': {'anonymized_name': {'description': 'Anonymized '
                                                                              'full '
                                                                              'name.',
                                                               'type': 'string'},
                                           'country': {'type': 'string'},
                                           'current_company': {'type': 'string'},
                                           'current_company_size': {'enum': ['1-10',
                                                                             '11-50',
                                                                             '51-200',
                                                                             '201-500',
                                                                             '501-1000',
                                                                             '1001-5000',
                                                                             '5001-10000',
                                                                             '10001+'],
                                                                    'type': 'string'},
                                           'current_industry': {'type': 'string'},
                                           'current_title': {'type': 'string'},
                                           'headline': {'description': 'One-line '
                                                                       'professional '
                                                                       'headline.',
                                                        'type': 'string'},
                                           'location': {'description': 'City, '
                                                                       'region/state.',
                                                        'type': 'string'},
                                           'summary': {'description': 'Multi-sentence '
                                                                      'professional '
                                                                      'summary.',
                                                       'type': 'string'},
                                           'years_of_experience': {'maximum': 50,
                                                                   'minimum': 0,
                                                                   'type': 'number'}},
                            'required': ['anonymized_name',
                                         'headline',
                                         'summary',
                                         'location',
                                         'country',
                                         'years_of_experience',
                                         'current_title',
                                         'current_company',
                                         'current_company_size',
                                         'current_industry'],
                            'type': 'object'},
                'redrob_signals': {'description': 'Simulated platform activity '
                                                  'and engagement signals from '
                                                  'the Redrob ecosystem.',
                                   'properties': {'applications_submitted_30d': {'minimum': 0,
                                                                                 'type': 'integer'},
                                                  'avg_response_time_hours': {'minimum': 0,
                                                                              'type': 'number'},
                                                  'connection_count': {'minimum': 0,
                                                                       'type': 'integer'},
                                                  'endorsements_received': {'minimum': 0,
                                                                            'type': 'integer'},
                                                  'expected_salary_range_inr_lpa': {'description': 'Expected '
                                                                                                   'salary '
                                                                                                   'in '
                                                                                                   'INR '
                                                                                                   'Lakhs '
                                                                                                   'Per '
                                                                                                   'Annum.',
                                                                                    'properties': {'max': {'minimum': 0,
                                                                                                           'type': 'number'},
                                                                                                   'min': {'minimum': 0,
                                                                                                           'type': 'number'}},
                                                                                    'required': ['min',
                                                                                                 'max'],
                                                                                    'type': 'object'},
                                                  'github_activity_score': {'description': '0-100 '
                                                                                           'score '
                                                                                           'based '
                                                                                           'on '
                                                                                           'commits, '
                                                                                           'PRs, '
                                                                                           'stars '
                                                                                           'in '
                                                                                           'last '
                                                                                           '12 '
                                                                                           'months. '
                                                                                           '-1 '
                                                                                           'if '
                                                                                           'no '
                                                                                           'GitHub '
                                                                                           'linked.',
                                                                            'maximum': 100,
                                                                            'minimum': -1,
                                                                            'type': 'number'},
                                                  'interview_completion_rate': {'description': 'Fraction '
                                                                                               'of '
                                                                                               'scheduled '
                                                                                               'interviews '
                                                                                               'actually '
                                                                                               'attended.',
                                                                                'maximum': 1,
                                                                                'minimum': 0,
                                                                                'type': 'number'},
                                                  'last_active_date': {'format': 'date',
                                                                       'type': 'string'},
                                                  'linkedin_connected': {'type': 'boolean'},
                                                  'notice_period_days': {'maximum': 180,
                                                                         'minimum': 0,
                                                                         'type': 'integer'},
                                                  'offer_acceptance_rate': {'description': 'Historical '
                                                                                           'offer '
                                                                                           'acceptance '
                                                                                           'rate. '
                                                                                           '-1 '
                                                                                           'if '
                                                                                           'no '
                                                                                           'offer '
                                                                                           'history.',
                                                                            'maximum': 1,
                                                                            'minimum': -1,
                                                                            'type': 'number'},
                                                  'open_to_work_flag': {'type': 'boolean'},
                                                  'preferred_work_mode': {'enum': ['remote',
                                                                                   'hybrid',
                                                                                   'onsite',
                                                                                   'flexible'],
                                                                          'type': 'string'},
                                                  'profile_completeness_score': {'description': 'Percentage '
                                                                                                'of '
                                                                                                'profile '
                                                                                                'completeness.',
                                                                                 'maximum': 100,
                                                                                 'minimum': 0,
                                                                                 'type': 'number'},
                                                  'profile_views_received_30d': {'minimum': 0,
                                                                                 'type': 'integer'},
                                                  'recruiter_response_rate': {'description': 'Fraction '
                                                                                             'of '

In [39]:
import json

candidate_path = "/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl"

candidates = []

with open(candidate_path,"r") as f:

    for line in f:

        candidates.append(json.loads(line))

print("Total candidates:",len(candidates))

Total candidates: 100000

In [40]:
candidate = candidates[0]

candidate.keys()

dict_keys(['candidate_id', 'profile', 'career_history', 'education', 'skills', 'certifications', 'languages', 'redrob_signals'])

In [41]:
import pandas as pd

rows = []

for c in candidates:

    p = c["profile"]

    r = c["redrob_signals"]

    row = {

        "candidate_id": c["candidate_id"],

        "headline": p["headline"],

        "summary": p["summary"],

        "location": p["location"],

        "country": p["country"],

        "current_title": p["current_title"],

        "current_company": p["current_company"],

        "current_industry": p["current_industry"],

        "years_of_experience": p["years_of_experience"],

        "current_company_size": p["current_company_size"],


        # behavioral

        "open_to_work":

            r["open_to_work_flag"],

        "github_score":

            r["github_activity_score"],

        "recruiter_response_rate":

            r["recruiter_response_rate"],

        "interview_completion_rate":

            r["interview_completion_rate"],

        "offer_acceptance_rate":

            r["offer_acceptance_rate"],

        "search_appearance":

            r["search_appearance_30d"],

        "saved_by_recruiters":

            r["saved_by_recruiters_30d"],

        "profile_views":

            r["profile_views_received_30d"],

        "notice_period":

            r["notice_period_days"],

        "willing_to_relocate":

            r["willing_to_relocate"]

    }

    rows.append(row)

df = pd.DataFrame(rows)

df.head()

,candidate_id,headline,summary,location,country,current_title,current_company,current_industry,years_of_experience,current_company_size,open_to_work,github_score,recruiter_response_rate,interview_completion_rate,offer_acceptance_rate,search_appearance,saved_by_recruiters,profile_views,notice_period,willing_to_relocate
0,CAND_0000001,"Backend Engineer | SQL, Spark, Cloud",Software / data professional with 6.9 years of...,Toronto,Canada,Backend Engineer,Mindtree,IT Services,6.9,10001+,True,9.2,0.34,0.71,0.58,249,4,23,60,False
1,CAND_0000002,Operations Manager | 12.5+ yrs experience,Professional with 12.5+ years of experience. M...,"Chennai, Tamil Nadu",India,Operations Manager,Wipro,IT Services,12.5,10001+,True,-1.0,0.29,0.62,-1.00,107,10,7,60,False
2,CAND_0000003,Customer Support | 1.1+ yrs experience,Professional with 1.1+ years of experience. I'...,Austin,USA,Customer Support,TCS,IT Services,1.1,10001+,False,-1.0,0.46,0.86,-1.00,28,4,1,150,False
3,CAND_0000004,Marketing Manager | Driving business outcomes,Professional with 3.8+ years of experience. My...,Sydney,Australia,Marketing Manager,Dunder Mifflin,Paper Products,3.8,201-500,False,-1.0,0.26,0.35,-1.00,5,8,3,120,True
4,CAND_0000005,Accountant | Helping teams scale,Professional with 11.0+ years of experience. I...,"Gurgaon, Haryana",India,Accountant,Stark Industries,Manufacturing,11.0,1001-5000,True,-1.0,0.37,0.74,-1.00,67,1,12,30,True

In [42]:
print(df.shape)

(100000, 20)

In [43]:
df["current_title"].value_counts().head(20)

current_title
Business Analyst        5833
HR Manager              5830
Mechanical Engineer     5791
Accountant              5764
Project Manager         5754
Customer Support        5750
Operations Manager      5744
Content Writer          5727
Sales Executive         5713
Civil Engineer          5702
Graphic Designer        5689
Marketing Manager       5524
Software Engineer       3450
Full Stack Developer    2873
Cloud Engineer          2836
Java Developer          2809
.NET Developer          2788
DevOps Engineer         2787
Mobile Developer        2757
Frontend Engineer       2738
Name: count, dtype: int64

In [44]:
df["years_of_experience"].describe()

count    100000.000000
mean          7.166319
std           3.824551
min           1.000000
25%           3.900000
50%           6.800000
75%           9.900000
max          16.900000
Name: years_of_experience, dtype: float64

In [45]:
from collections import Counter

all_skills = []

for c in candidates:

    for skill in c["skills"]:

        all_skills.append(skill["name"])


skill_counts = Counter(all_skills)

skill_counts.most_common(50)

[('HTML', 12246),
 ('Databricks', 12244),
 ('Redux', 12222),
 ('Terraform', 12187),
 ('Angular', 12173),
 ('Figma', 12157),
 ('Salesforce CRM', 12157),
 ('Vue.js', 12142),
 ('Sales', 12138),
 ('Accounting', 12136),
 ('Agile', 12135),
 ('Kafka', 12114),
 ('Excel', 12109),
 ('BigQuery', 12108),
 ('CI/CD', 12108),
 ('Project Management', 12106),
 ('Airflow', 12105),
 ('AWS', 12104),
 ('Flask', 12104),
 ('Scrum', 12083),
 ('Illustrator', 12072),
 ('Kubernetes', 12071),
 ('ETL', 12068),
 ('CSS', 12065),
 ('Docker', 12062),
 ('Next.js', 12058),
 ('Apache Beam', 12054),
 ('Java', 12049),
 ('Go', 12049),
 ('TypeScript', 12048),
 ('JavaScript', 12047),
 ('dbt', 12046),
 ('REST APIs', 12040),
 ('Spark', 12038),
 ('Marketing', 12037),
 ('Tally', 12030),
 ('GraphQL', 12027),
 ('Snowflake', 12027),
 ('Webpack', 12026),
 ('Six Sigma', 11991),
 ('SEO', 11990),
 ('SAP', 11989),
 ('GCP', 11983),
 ('PostgreSQL', 11983),
 ('Rust', 11960),
 ('Apache Flink', 11958),
 ('gRPC', 11957),
 ('Content Writing', 11948),
 ('SQL', 11935),
 ('Hadoop', 11931)]

In [46]:
ai_keywords = [

    "AI",

    "Machine Learning",

    "ML",

    "Data Scientist",

    "NLP",

    "Generative",

    "LLM",

    "Applied Scientist",

    "Deep Learning"

]

count = 0

for title in df["current_title"]:

    title = str(title).lower()

    if any(k.lower() in title for k in ai_keywords):

        count += 1


print("AI related candidates:",count)

AI related candidates: 998

In [47]:
AI_KEYWORDS = [

    "AI",

    "Artificial Intelligence",

    "Machine Learning",

    "ML",

    "Deep Learning",

    "NLP",

    "Generative",

    "LLM",

    "Data Scientist",

    "Applied Scientist",

    "AI Engineer",

    "ML Engineer"

]


ai_candidates = []

for c in candidates:

    title = c["profile"]["current_title"]

    headline = c["profile"]["headline"]

    summary = c["profile"]["summary"]


    text = f"{title} {headline} {summary}".lower()


    if any(

        k.lower() in text

        for k in AI_KEYWORDS

    ):

        ai_candidates.append(c)



print(len(ai_candidates))

100000

In [48]:
from collections import Counter

all_skills = []

for c in candidates:

    for skill in c["skills"]:

        all_skills.append(skill["name"])

skill_counts = Counter(all_skills)

skill_counts.most_common(50)

[('HTML', 12246),
 ('Databricks', 12244),
 ('Redux', 12222),
 ('Terraform', 12187),
 ('Angular', 12173),
 ('Figma', 12157),
 ('Salesforce CRM', 12157),
 ('Vue.js', 12142),
 ('Sales', 12138),
 ('Accounting', 12136),
 ('Agile', 12135),
 ('Kafka', 12114),
 ('Excel', 12109),
 ('BigQuery', 12108),
 ('CI/CD', 12108),
 ('Project Management', 12106),
 ('Airflow', 12105),
 ('AWS', 12104),
 ('Flask', 12104),
 ('Scrum', 12083),
 ('Illustrator', 12072),
 ('Kubernetes', 12071),
 ('ETL', 12068),
 ('CSS', 12065),
 ('Docker', 12062),
 ('Next.js', 12058),
 ('Apache Beam', 12054),
 ('Java', 12049),
 ('Go', 12049),
 ('TypeScript', 12048),
 ('JavaScript', 12047),
 ('dbt', 12046),
 ('REST APIs', 12040),
 ('Spark', 12038),
 ('Marketing', 12037),
 ('Tally', 12030),
 ('GraphQL', 12027),
 ('Snowflake', 12027),
 ('Webpack', 12026),
 ('Six Sigma', 11991),
 ('SEO', 11990),
 ('SAP', 11989),
 ('GCP', 11983),
 ('PostgreSQL', 11983),
 ('Rust', 11960),
 ('Apache Flink', 11958),
 ('gRPC', 11957),
 ('Content Writing', 11948),
 ('SQL', 11935),
 ('Hadoop', 11931)]

In [49]:
titles = sorted(df["current_title"].unique())

for t in titles:

    if (

        "data" in t.lower()

        or "scientist" in t.lower()

        or "machine" in t.lower()

        or "ai" in t.lower()

        or "ml" in t.lower()

        or "nlp" in t.lower()

    ):

        print(t)

AI Engineer
AI Research Engineer
AI Specialist
Applied ML Engineer
Data Analyst
Data Engineer
Data Scientist
Junior ML Engineer
Lead AI Engineer
ML Engineer
Machine Learning Engineer
NLP Engineer
Senior AI Engineer
Senior Applied Scientist
Senior Data Engineer
Senior Data Scientist
Senior Machine Learning Engineer
Senior NLP Engineer
Senior Software Engineer (ML)
Staff Machine Learning Engineer

In [50]:
TITLE_WEIGHTS = {

    "Senior AI Engineer":100,

    "Lead AI Engineer":95,

    "Staff Machine Learning Engineer":95,

    "Senior Machine Learning Engineer":92,

    "Senior Applied Scientist":90,

    "AI Research Engineer":88,

    "Machine Learning Engineer":85,

    "Applied ML Engineer":85,

    "ML Engineer":82,

    "AI Engineer":80,

    "Senior NLP Engineer":78,

    "NLP Engineer":75,

    "Senior Data Scientist":72,

    "Data Scientist":65,

    "Senior Software Engineer (ML)":60,

    "Data Engineer":40,

    "Senior Data Engineer":45,

    "Data Analyst":20
}

In [51]:
def get_title_score(title):

    return TITLE_WEIGHTS.get(title,0)

In [52]:
for t in [

    "Senior AI Engineer",

    "Machine Learning Engineer",

    "Data Scientist",

    "Data Analyst"

]:

    print(t,

          get_title_score(t))

Senior AI Engineer 100
Machine Learning Engineer 85
Data Scientist 65
Data Analyst 20

In [55]:
df["title_score"] = df["current_title"].apply(

    get_title_score

)

df[

    [

        "candidate_id",

        "current_title",

        "title_score"

    ]

].head()

   candidate_id       current_title  title_score
0  CAND_0000001    Backend Engineer            0
1  CAND_0000002  Operations Manager            0
2  CAND_0000003    Customer Support            0
3  CAND_0000004   Marketing Manager            0
4  CAND_0000005          Accountant            0

In [59]:
def get_title_score(title):

    title = str(title).lower()


    if "senior ai engineer" in title:
        return 100

    elif "lead ai engineer" in title:
        return 95

    elif "staff machine learning engineer" in title:
        return 95

    elif "senior machine learning engineer" in title:
        return 92

    elif "senior applied scientist" in title:
        return 90

    elif "ai research engineer" in title:
        return 88

    elif "machine learning engineer" in title:
        return 85

    elif "applied ml engineer" in title:
        return 85

    elif "ml engineer" in title:
        return 82

    elif "ai engineer" in title:
        return 80

    elif "senior nlp engineer" in title:
        return 78

    elif "nlp engineer" in title:
        return 75

    elif "senior data scientist" in title:
        return 72

    elif "data scientist" in title:
        return 65

    elif "senior software engineer" in title and "ml" in title:
        return 60

    elif "data engineer" in title:
        return 40

    elif "senior data engineer" in title:
        return 45

    elif "data analyst" in title:
        return 20

    else:

        return 0

In [60]:
df["title_score"] = df["current_title"].apply(

    get_title_score

)

df.sort_values(

    "title_score",

    ascending=False

)[

    [

        "candidate_id",

        "current_title",

        "title_score"

    ]

].head(20)

       candidate_id                     current_title  title_score
6566   CAND_0006567                Senior AI Engineer          100
5537   CAND_0005538                Senior AI Engineer          100
71973  CAND_0071974                Senior AI Engineer          100
2024   CAND_0002025                Senior AI Engineer          100
94758  CAND_0094759                  Lead AI Engineer           95
80765  CAND_0080766   Staff Machine Learning Engineer           95
61256  CAND_0061257   Staff Machine Learning Engineer           95
60071  CAND_0060072   Staff Machine Learning Engineer           95
88024  CAND_0088025   Staff Machine Learning Engineer           95
68350  CAND_0068351                  Lead AI Engineer           95
81845  CAND_0081846                  Lead AI Engineer           95
41610  CAND_0041611   Staff Machine Learning Engineer           95
77336  CAND_0077337   Staff Machine Learning Engineer           95
93192  CAND_0093193  Senior Machine Learning Engineer           92
55904  CAND_0055905  Senior Machine Learning Engineer           92
18498  CAND_0018499  Senior Machine Learning Engineer           92
7410   CAND_0007411  Senior Machine Learning Engineer           92
46524  CAND_0046525  Senior Machine Learning Engineer           92
93546  CAND_0093547  Senior Machine Learning Engineer           92
86021  CAND_0086022          Senior Applied Scientist           90

In [61]:
from collections import Counter

skill_counts = Counter()

for c in candidates:

    for skill in c["skills"]:

        skill_counts[skill["name"]] += 1


skill_counts.most_common(50)

[('HTML', 12246),
 ('Databricks', 12244),
 ('Redux', 12222),
 ('Terraform', 12187),
 ('Angular', 12173),
 ('Figma', 12157),
 ('Salesforce CRM', 12157),
 ('Vue.js', 12142),
 ('Sales', 12138),
 ('Accounting', 12136),
 ('Agile', 12135),
 ('Kafka', 12114),
 ('Excel', 12109),
 ('BigQuery', 12108),
 ('CI/CD', 12108),
 ('Project Management', 12106),
 ('Airflow', 12105),
 ('AWS', 12104),
 ('Flask', 12104),
 ('Scrum', 12083),
 ('Illustrator', 12072),
 ('Kubernetes', 12071),
 ('ETL', 12068),
 ('CSS', 12065),
 ('Docker', 12062),
 ('Next.js', 12058),
 ('Apache Beam', 12054),
 ('Java', 12049),
 ('Go', 12049),
 ('TypeScript', 12048),
 ('JavaScript', 12047),
 ('dbt', 12046),
 ('REST APIs', 12040),
 ('Spark', 12038),
 ('Marketing', 12037),
 ('Tally', 12030),
 ('GraphQL', 12027),
 ('Snowflake', 12027),
 ('Webpack', 12026),
 ('Six Sigma', 11991),
 ('SEO', 11990),
 ('SAP', 11989),
 ('GCP', 11983),
 ('PostgreSQL', 11983),
 ('Rust', 11960),
 ('Apache Flink', 11958),
 ('gRPC', 11957),
 ('Content Writing', 11948),
 ('SQL', 11935),
 ('Hadoop', 11931)]

In [62]:
AI_TITLES = [

    "AI Engineer",

    "AI Research Engineer",

    "AI Specialist",

    "Applied ML Engineer",

    "Data Scientist",

    "Machine Learning Engineer",

    "ML Engineer",

    "NLP Engineer",

    "Senior AI Engineer",

    "Senior Applied Scientist",

    "Senior Data Scientist",

    "Senior Machine Learning Engineer",

    "Senior NLP Engineer",

    "Senior Software Engineer (ML)",

    "Staff Machine Learning Engineer"

]


ai_candidates = [

    c

    for c in candidates

    if c["profile"]["current_title"]

    in AI_TITLES

]


print(len(ai_candidates))

864

In [64]:
from collections import Counter

ai_skill_counts = Counter()

for c in ai_candidates:

    for skill in c["skills"]:

        ai_skill_counts[skill["name"]] += 1


ai_skill_counts.most_common(100)

[('Image Classification', 243),
 ('Feature Engineering', 241),
 ('MLflow', 237),
 ('Diffusion Models', 235),
 ('OpenCV', 230),
 ('MLOps', 230),
 ('GANs', 228),
 ('Time Series', 227),
 ('Object Detection', 227),
 ('Speech Recognition', 226),
 ('ASR', 225),
 ('Forecasting', 225),
 ('TTS', 223),
 ('BentoML', 222),
 ('Kubeflow', 220),
 ('Computer Vision', 220),
 ('Data Science', 220),
 ('YOLO', 219),
 ('Reinforcement Learning', 219),
 ('Weights & Biases', 218),
 ('Statistical Modeling', 215),
 ('CNN', 200),
 ('Qdrant', 188),
 ('PyTorch', 186),
 ('Weaviate', 185),
 ('Python', 184),
 ('NLP', 183),
 ('BM25', 183),
 ('OpenSearch', 182),
 ('LoRA', 182),
 ('Semantic Search', 181),
 ('Hugging Face Transformers', 180),
 ('Deep Learning', 179),
 ('Pinecone', 176),
 ('QLoRA', 176),
 ('pgvector', 171),
 ('Milvus', 170),
 ('LangChain', 170),
 ('Elasticsearch', 169),
 ('Recommendation Systems', 168),
 ('PEFT', 167),
 ('Embeddings', 166),
 ('Machine Learning', 166),
 ('Sentence Transformers', 163),
 ('Learning to Rank', 163),
 ('scikit-learn', 162),
 ('Prompt Engineering', 159),
 ('Vector Search', 158),
 ('Information Retrieval', 156),
 ('RAG', 156),
 ('Fine-tuning LLMs', 155),
 ('LLMs', 155),
 ('TensorFlow', 152),
 ('FAISS', 149),
 ('Haystack', 146),
 ('LlamaIndex', 145),
 ('Kubernetes', 43),
 ('Apache Flink', 42),
 ('Vue.js', 42),
 ('Redux', 41),
 ('Databricks', 40),
 ('Hadoop', 40),
 ('JavaScript', 38),
 ('SQL', 38),
 ('Next.js', 37),
 ('Flask', 37),
 ('gRPC', 37),
 ('Azure', 37),
 ('Java', 36),
 ('CSS', 36),
 ('Content Writing', 36),
 ('Apache Beam', 36),
 ('Tally', 36),
 ('Illustrator', 35),
 ('Tailwind', 35),
 ('Terraform', 35),
 ('Agile', 35),
 ('Airflow', 34),
 ('Photoshop', 34),
 ('MongoDB', 34),
 ('Project Management', 33),
 ('Accounting', 33),
 ('ETL', 33),
 ('dbt', 33),
 ('Kafka', 33),
 ('Docker', 32),
 ('GCP', 32),
 ('Rust', 32),
 ('Microservices', 32),
 ('SEO', 32),
 ('Marketing', 32),
 ('PostgreSQL', 31),
 ('Redis', 31),
 ('PowerPoint', 31),
 ('Node.js', 31),
 ('Webpack', 31),
 ('Salesforce CRM', 30),
 ('CI/CD', 30),
 ('Angular', 30),
 ('BigQuery', 29)]

In [65]:
SKILL_WEIGHTS = {

    # Core AI

    "LLM":15,

    "Large Language Models":15,

    "Generative AI":15,

    "Embeddings":14,

    "Retrieval":14,

    "Ranking":14,

    "RAG":13,

    "NLP":12,

    "Prompt Engineering":12,

    "LangChain":12,

    # Frameworks

    "Python":8,

    "PyTorch":8,

    "Transformers":8,

    "Machine Learning":8,

    "Deep Learning":8,

    # Vector DBs

    "Milvus":10,

    "Pinecone":10,

    "Weaviate":10,

    "Vector Search":10,

}

In [69]:
def get_skill_score(skills):

    score = 0

    candidate_skills = {

        s["name"].lower()

        for s in skills

    }


    for skill,weight in SKILL_WEIGHTS.items():

        if skill.lower() in candidate_skills:

            score += weight


    return score

In [70]:
sample = candidates[0]

print(sample["skills"])

print(

    get_skill_score(

        sample["skills"]

    )

)

[{'name': 'Tailwind', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 13}, {'name': 'NLP', 'proficiency': 'advanced', 'endorsements': 37, 'duration_months': 26}, {'name': 'Image Classification', 'proficiency': 'advanced', 'endorsements': 7, 'duration_months': 40}, {'name': 'Fine-tuning LLMs', 'proficiency': 'advanced', 'endorsements': 21, 'duration_months': 36}, {'name': 'Weights & Biases', 'proficiency': 'intermediate', 'endorsements': 13, 'duration_months': 30}, {'name': 'Speech Recognition', 'proficiency': 'advanced', 'endorsements': 52, 'duration_months': 33}, {'name': 'Photoshop', 'proficiency': 'intermediate', 'endorsements': 8, 'duration_months': 24}, {'name': 'TTS', 'proficiency': 'advanced', 'endorsements': 56, 'duration_months': 60}, {'name': 'LoRA', 'proficiency': 'intermediate', 'endorsements': 0, 'duration_months': 28}, {'name': 'Apache Beam', 'proficiency': 'intermediate', 'endorsements': 4, 'duration_months': 9}, {'name': 'AWS', 'proficiency': 'beginner', 'endorsements': 5, 'duration_months': 8}, {'name': 'Flask', 'proficiency': 'beginner', 'endorsements': 15, 'duration_months': 15}, {'name': 'BentoML', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 36}, {'name': 'Milvus', 'proficiency': 'advanced', 'endorsements': 40, 'duration_months': 35}, {'name': 'GANs', 'proficiency': 'advanced', 'endorsements': 12, 'duration_months': 19}, {'name': 'Statistical Modeling', 'proficiency': 'intermediate', 'endorsements': 9, 'duration_months': 8}, {'name': 'GCP', 'proficiency': 'beginner', 'endorsements': 7, 'duration_months': 2}]
22

In [71]:
df["exp_score"] = df[

    "years_of_experience"

].apply(

    get_exp_score

)

NameError: name 'get_exp_score' is not defined

In [76]:
def get_exp_score(exp):

    if 5 <= exp <= 9:
        return 100

    elif exp == 4 or exp == 10:
        return 80

    elif exp == 3 or exp == 11:
        return 60

    else:
        return 20

In [78]:
df["exp_score"] = df["years_of_experience"].apply(get_exp_score)

In [79]:
df[
    [
        "candidate_id",
        "years_of_experience",
        "exp_score"
    ]
].head(10)

   candidate_id  years_of_experience  exp_score
0  CAND_0000001                  6.9        100
1  CAND_0000002                 12.5         20
2  CAND_0000003                  1.1         20
3  CAND_0000004                  3.8         20
4  CAND_0000005                 11.0         60
5  CAND_0000006                  6.0        100
6  CAND_0000007                  5.5        100
7  CAND_0000008                  3.6         20
8  CAND_0000009                 11.0         60
9  CAND_0000010                  4.6         20

In [81]:
df["behavior_score"] = (

      df["github_score"] * 0.25

    + df["recruiter_response_rate"] * 0.20

    + df["interview_completion_rate"] * 0.20

    + df["offer_acceptance_rate"] * 0.15

    + df["search_appearance"] * 0.10

    + df["saved_by_recruiters"] * 0.10

)

In [82]:
df["final_score"] = (

      df["skill_score"] * 0.40

    + df["exp_score"] * 0.20

    + df["title_score"] * 0.15

    + df["behavior_score"] * 0.15

)

KeyError: 'skill_score'

In [83]:
print(df.columns.tolist())

['candidate_id', 'headline', 'summary', 'location', 'country', 'current_title', 'current_company', 'current_industry', 'years_of_experience', 'current_company_size', 'open_to_work', 'github_score', 'recruiter_response_rate', 'interview_completion_rate', 'offer_acceptance_rate', 'search_appearance', 'saved_by_recruiters', 'profile_views', 'notice_period', 'willing_to_relocate', 'title_score', 'exp_score', 'behavior_score']

In [86]:
def get_skill_score(skills):

    score = 0

    candidate_skills = {

        s["name"].lower()

        for s in skills

    }

    for skill,weight in SKILL_WEIGHTS.items():

        if skill.lower() in candidate_skills:

            score += weight

    return score

In [ ]:
skill_scores = []

for c in candidates:

    skill_scores.append(

        get_skill_score(

            c["skills"]

        )

    )

In [87]:
skill_scores = []

for c in candidates:

    skill_scores.append(

        get_skill_score(

            c["skills"]

        )

    )

df["skill_score"] = skill_scores

In [88]:
df[

    [

        "candidate_id",

        "current_title",

        "skill_score"

    ]

].head()

   candidate_id       current_title  skill_score
0  CAND_0000001    Backend Engineer           22
1  CAND_0000002  Operations Manager            0
2  CAND_0000003    Customer Support            0
3  CAND_0000004   Marketing Manager            0
4  CAND_0000005          Accountant            0

In [90]:
df["final_score"] = (

      df["skill_score"] * 0.40

    + df["exp_score"] * 0.20

    + df["title_score"] * 0.15

    + df["behavior_score"] * 0.15

)

In [91]:
df["skill_score"].describe()

count    100000.000000
mean          4.476150
std          12.290423
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max          83.000000
Name: skill_score, dtype: float64

In [92]:
import pandas as pd

sample = pd.read_csv(
"/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_submission.csv"
)

print(sample.columns)
sample.head()

Index(['candidate_id', 'rank', 'score', 'reasoning'], dtype='object')

,candidate_id,rank,score,reasoning
0,CAND_0004989,1,0.992,HR Manager with 6.1 yrs; 9 AI core skills; res...
1,CAND_0001195,2,0.984,HR Manager with 8.7 yrs; 9 AI core skills; res...
2,CAND_0003114,3,0.976,ML Engineer with 6.4 yrs; 4 AI core skills; re...
3,CAND_0000339,4,0.968,Content Writer with 8.3 yrs; 8 AI core skills;...
4,CAND_0001082,5,0.960,HR Manager with 5.0 yrs; 8 AI core skills; res...

In [93]:
with open(
"/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/validate_submission.py",
"r"
) as f:

    for i in range(100):
        print(f.readline(), end="")

#!/usr/bin/env python3
"""
Validate submission CSV per challenge rules (sections 2–3).
Row 1 = header. Rows 2–101 = exactly 100 data rows. CSV only.
"""

import csv
import re
import sys
from pathlib import Path

REQUIRED_HEADER = ["candidate_id", "rank", "score", "reasoning"]
CANDIDATE_ID_PATTERN = re.compile(r"^CAND_[0-9]{7}$")
DATA_ROW_START = 2
EXPECTED_DATA_ROWS = 100


def validate_submission(csv_path):
    errors = []
    path = Path(csv_path)

    if path.suffix.lower() != ".csv":
        errors.append("Filename must use a .csv extension.")
    elif not path.stem:
        errors.append("Filename must be your registered participant ID (e.g. team_xxx.csv).")

    try:
        with open(path, "r", encoding="utf-8", newline="") as f:
            reader = csv.reader(f)

            try:
                header = next(reader)
            except StopIteration:
                errors.append("Row 1 must be the header row; file is empty.")
                return errors

            # Row 1: column names and their order come from this line only
            if header != REQUIRED_HEADER:
                errors.append(
                    "Row 1 (header) must be exactly:\n"
                    f"  {','.join(REQUIRED_HEADER)}\n"
                    f"Found:\n"
                    f"  {','.join(header)}"
                )

            data_rows = []
            for row in reader:
                if any(cell.strip() for cell in row):
                    data_rows.append(row)

    except UnicodeDecodeError:
        errors.append("File must be UTF-8 encoded.")
        return errors
    except OSError as e:
        errors.append(f"Cannot read file: {e}")
        return errors

    n = len(data_rows)
    if n != EXPECTED_DATA_ROWS:
        errors.append(
            f"After the header (row 1), there must be exactly {EXPECTED_DATA_ROWS} "
            f"data rows (rows {DATA_ROW_START}–{DATA_ROW_START + EXPECTED_DATA_ROWS - 1}); "
            f"found {n}."
        )

    seen_ids = set()
    seen_ranks = set()
    by_rank = []

    for i, cells in enumerate(data_rows):
        row_num = DATA_ROW_START + i

        if len(cells) != len(REQUIRED_HEADER):
            errors.append(
                f"Row {row_num}: expected {len(REQUIRED_HEADER)} columns "
                f"({','.join(REQUIRED_HEADER)}), got {len(cells)}."
            )
            continue

        row = dict(zip(REQUIRED_HEADER, cells))
        cid = row["candidate_id"].strip()
        rank_s = row["rank"].strip()
        score_s = row["score"].strip()

        if not cid:
            errors.append(f"Row {row_num}: candidate_id is required.")
        elif not CANDIDATE_ID_PATTERN.match(cid):
            errors.append(
                f"Row {row_num}: candidate_id must be CAND_XXXXXXX (7 digits)."
            )
        elif cid in seen_ids:
            errors.append(f"Row {row_num}: duplicate candidate_id '{cid}'.")
        else:
            seen_ids.add(cid)

        try:
            rank = int(rank_s)
            if str(rank) != rank_s:
                raise ValueError
            if not 1 <= rank <= 100:

In [98]:
df["final_score"] = (
    0.5 * df["skill_score"]
    + 0.3 * df["title_score"]
    + 0.2 * df["exp_score"]
)

In [104]:
top100 = df.sort_values(
    "final_score",
    ascending=False
).head(100).copy()

In [105]:
top100["rank"] = range(1,101)

In [107]:
mn = top100["final_score"].min()
mx = top100["final_score"].max()

top100["score"] = (

    (top100["final_score"] - mn)

    /

    (mx - mn)

).round(3)

In [109]:
top100["reasoning"] = (

    top100["current_title"]

    + " with "

    + top100["years_of_experience"]

      .astype(str)

    + " yrs; "

    + "skill score "

    + top100["skill_score"]

      .astype(str)

    + "; strong AI profile"

)

In [111]:
submission = top100[

    [

        "candidate_id",

        "rank",

        "score",

        "reasoning"

    ]

]

In [112]:
submission.head()

,candidate_id,rank,score,reasoning
60071,CAND_0060072,1,1.000,Staff Machine Learning Engineer with 5.7 yrs; ...
18498,CAND_0018499,2,0.855,Senior Machine Learning Engineer with 7.2 yrs;...
2024,CAND_0002025,3,0.851,Senior AI Engineer with 5.9 yrs; skill score 7...
86021,CAND_0086022,4,0.777,Senior Applied Scientist with 5.3 yrs; skill s...
88024,CAND_0088025,5,0.628,Staff Machine Learning Engineer with 8.6 yrs; ...

In [113]:
submission.to_csv(
    "AIndia.csv",
    index=False
)

print("Submission file saved successfully!")

Submission file saved successfully!

In [114]:
import pandas as pd

check = pd.read_csv("AIndia.csv")

print(check.shape)
check.head()

(100, 4)

,candidate_id,rank,score,reasoning
0,CAND_0060072,1,1.000,Staff Machine Learning Engineer with 5.7 yrs; ...
1,CAND_0018499,2,0.855,Senior Machine Learning Engineer with 7.2 yrs;...
2,CAND_0002025,3,0.851,Senior AI Engineer with 5.9 yrs; skill score 7...
3,CAND_0086022,4,0.777,Senior Applied Scientist with 5.3 yrs; skill s...
4,CAND_0088025,5,0.628,Staff Machine Learning Engineer with 8.6 yrs; ...

In [116]:
!python "/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/validate_submission.py" AIndia.csv

Validation failed (24 issue(s)):

- Equal scores at ranks 11 and 12: tie-break requires candidate_id ascending ('CAND_0045250' > 'CAND_0030031').
- Equal scores at ranks 13 and 14: tie-break requires candidate_id ascending ('CAND_0042029' > 'CAND_0029367').
- Equal scores at ranks 14 and 15: tie-break requires candidate_id ascending ('CAND_0029367' > 'CAND_0007052').
- Equal scores at ranks 24 and 25: tie-break requires candidate_id ascending ('CAND_0074326' > 'CAND_0046353').
- Equal scores at ranks 27 and 28: tie-break requires candidate_id ascending ('CAND_0094759' > 'CAND_0049538').
- Equal scores at ranks 33 and 34: tie-break requires candidate_id ascending ('CAND_0055905' > 'CAND_0011263').
- Equal scores at ranks 36 and 37: tie-break requires candidate_id ascending ('CAND_0070202' > 'CAND_0008239').
- Equal scores at ranks 41 and 42: tie-break requires candidate_id ascending ('CAND_0076163' > 'CAND_0013536').
- Equal scores at ranks 49 and 50: tie-break requires candidate_id ascending ('CAND_0078002' > 'CAND_0015528').
- Equal scores at ranks 51 and 52: tie-break requires candidate_id ascending ('CAND_0068351' > 'CAND_0051630').
- Equal scores at ranks 54 and 55: tie-break requires candidate_id ascending ('CAND_0051466' > 'CAND_0010541').
- Equal scores at ranks 57 and 58: tie-break requires candidate_id ascending ('CAND_0042008' > 'CAND_0018653').
- Equal scores at ranks 61 and 62: tie-break requires candidate_id ascending ('CAND_0028287' > 'CAND_0006567').
- Equal scores at ranks 64 and 65: tie-break requires candidate_id ascending ('CAND_0065514' > 'CAND_0016801').
- Equal scores at ranks 68 and 69: tie-break requires candidate_id ascending ('CAND_0032271' > 'CAND_0011687').
- Equal scores at ranks 75 and 76: tie-break requires candidate_id ascending ('CAND_0069232' > 'CAND_0028422').
- Equal scores at ranks 77 and 78: tie-break requires candidate_id ascending ('CAND_0032996' > 'CAND_0021836').
- Equal scores at ranks 79 and 80: tie-break requires candidate_id ascending ('CAND_0089552' > 'CAND_0062247').
- Equal scores at ranks 86 and 87: tie-break requires candidate_id ascending ('CAND_0095213' > 'CAND_0049615').
- Equal scores at ranks 88 and 89: tie-break requires candidate_id ascending ('CAND_0091745' > 'CAND_0038368').
- Equal scores at ranks 92 and 93: tie-break requires candidate_id ascending ('CAND_0050876' > 'CAND_0020877').
- Equal scores at ranks 95 and 96: tie-break requires candidate_id ascending ('CAND_0076412' > 'CAND_0075491').
- Equal scores at ranks 98 and 99: tie-break requires candidate_id ascending ('CAND_0076482' > 'CAND_0005649').
- Equal scores at ranks 99 and 100: tie-break requires candidate_id ascending ('CAND_0005649' > 'CAND_0002120').

In [118]:
top100 = df.sort_values(
    by=["final_score", "candidate_id"],
    ascending=[False, True]
).head(100).copy()

In [120]:
top100["rank"] = range(1, 101)

In [122]:
mn = top100["final_score"].min()
mx = top100["final_score"].max()

top100["score"] = (
    (top100["final_score"] - mn)
    / (mx - mn)
).round(6)

In [124]:
top100["reasoning"] = (
    top100["current_title"]
    + " with "
    + top100["years_of_experience"].astype(str)
    + " yrs; skill score "
    + top100["skill_score"].astype(str)
    + "; strong AI profile"
)

In [126]:
submission = top100[
    [
        "candidate_id",
        "rank",
        "score",
        "reasoning"
    ]
]

In [129]:
submission.to_csv(
    "AIndia.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [130]:
!python "/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/validate_submission.py" AIndia.csv

Submission is valid.

In [131]:
from google.colab import files

files.download("AIndia.csv")